<?php
$title = 'Agrega libro';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$libro = $form->get('nombre');
$libro->setAttribute('class', 'form-control');
$libro->setAttribute('placeholder', 'Libro nombre');

// This provides a default CSS class and placeholder text for the artist element:
$precio = $form->get('precio');
$precio->setAttribute('class', 'form-control');
$precio->setAttribute('placeholder', 'Precio');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('libro', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($libro) ?>
    <?= $this->formElement($libro) ?>
    <?= $this->formElementErrors()->render($libro, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($precio) ?>
    <?= $this->formElement($precio) ?>
    <?= $this->formElementErrors()->render($precio, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();