<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Editar';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$libro = $form->get('nombre');
$libro->setAttribute('class', 'form-control');
$libro->setAttribute('placeholder', 'Nombre del libro');

$precio = $form->get('precio');
$precio->setAttribute('class', 'form-control');
$precio->setAttribute('placeholder', 'Precio');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('libro', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($libro) ?>
    <?= $this->formElement($libro) ?>
    <?= $this->formElementErrors()->render($libro, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($precio) ?>
    <?= $this->formElement($precio) ?>
    <?= $this->formElementErrors()->render($precio, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();