<p>
    <a href="<?= $this->url('libro', ['action' => 'add']) ?>">Agregar libro</a>
</p>

<div class='row'>
<table class="table table-hover">
 <thead>
   <tr>
     <th scope="col">Id</th>
     <th scope="col">Nombre</th>
     <th scope="col">Precio</th>
   
   </tr>
 </thead>
 <tbody>
   <?php if(count($libros)>0):?>
       <?php foreach ($libros as  $libro): ?>

       <tr>
         <th><?php echo $libro->getId();?></th>
         <td><?php echo $libro->getNombre();?></td>
         <td><?php echo $libro->getPrecio();?></td>

         
         <td><a href="<?php echo $this->url('libro',['action' => 'edit', 'id' => $libro->getId()]);?>" class="label label-primary">ACTUALIZAR</a></td>
       
         <td><a href="<?php echo $this->url('libro',['action' => 'delete', 'id' => $libro->getId()]);?>" class="label label-danger">ELIMINAR</a></td>
       </tr>
 



        <?php endforeach; ?>
   <?php else: ?>
       <tr>
           <td>No records found!</td>
       </tr>

  <?php endif;?>
 </tbody>
</table>